name: audio_tools
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.0.0
  - torchaudio>=2.0.0
  - torchvision>=0.15.0
  - numpy>=1.24.0
  - scipy>=1.10.0
  - matplotlib>=3.7.0
  - ffmpeg  # For audio processing
  - pip
  - pip:
    - librosa>=0.10.0
    - soundfile>=0.12.1
    - transformers>=4.30.0
    - sentence-transformers>=2.2.0
    - tokenizers>=0.13.0
    - pedalboard>=0.7.0
    - crepe>=0.0.12
    - wandb>=0.15.0
    - tqdm>=4.65.0
    - accelerate>=0.20.0
    - einops>=0.7.0
    - Pillow>=9.5.0
